export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const CHECK_TOKEN = 'CHECK_TOKEN';
export const SET_CATALOG_DATA = 'SET_CATALOG_DATA';
export const SET_CATALOG_ID = 'SET_CATALOG_ID';
export const SET_CATALOG_PRODUCTS_DATA = 'SET_CATALOG_PRODUCTS_DATA';
export const SET_PRODUCT_ID = 'SET_PRODUCT_ID';
export const SET_SINGLE_PRODUCT_DATA = 'SET_SINGLE_PRODUCT_DATA';
export const SET_BASKET_INFO = 'SET_BASKET_INFO';
export const SET_PROFILE_INFO = 'SET_PROFILE_INFO';
export const SET_MY_ORDERS_INFO = 'SET_MY_ORDERS_INFO';
export const SET_SEARCH_PRODUCT = 'SET_SEARCH_PRODUCT';

